FROM node:latest as node
WORKDIR /app
COPY ./dist .
COPY ./package* .
RUN npm install
RUN npm run build --prod

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=node /app/dist/frontend /usr/share/nginx/html